export enum QuoteStatus {
  PENDING_HUMAN_APPROVAL = 'PENDING_HUMAN_APPROVAL',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  EXECUTED = 'EXECUTED',
}

export enum QuoteEventType {
  QUOTE_CREATED = 'QUOTE_CREATED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  EXECUTED = 'EXECUTED',
  EXECUTION_REPLAYED = 'EXECUTION_REPLAYED',
}
