export enum QuoteStatus {
  PENDING_HUMAN_APPROVAL = 'PENDING_HUMAN_APPROVAL',
  APPROVED_BY_HUMAN = 'APPROVED_BY_HUMAN',
  REJECTED = 'REJECTED',
  EXECUTED = 'EXECUTED',
}

export enum QuoteEventType {
  QUOTE_CREATED = 'QUOTE_CREATED',
  APPROVED_BY_HUMAN = 'APPROVED_BY_HUMAN',
  REJECTED = 'REJECTED',
  QUOTE_EXECUTED = 'QUOTE_EXECUTED',
}
